### ISSUE TITLE
Printing not possible

### ISSUE THREAD

**Issue by ponchofiesta** [alandmoore/wcgbrowser#12]
There is a bug in print_webpage method.
`self.print_settings` is not set. I think it has to be replaced by `self.config.get("print_settings")`.
I currently fixed it quick&dirty by setting `self.print_settings = self.config.get("print_settings")` and changing some ifs

**Comment by alandmoore** [comment]
Thanks for catching this.  Should be fixed in the latest commit.

**Comment by ponchofiesta** [comment]
Still not working for me. My .yaml has print_settings commented out.

```
# python browser.py -c primo-tu.yaml 
QTt5 import error
Traceback (most recent call last):
  File "browser.py", line 929, in print_webpage
    if print_settings.get("mode") == "high":
AttributeError: 'NoneType' object has no attribute 'get'
```

(line number may differ from yours as I use the same_window popup modification)

**Comment by alandmoore** [comment]
The logic in that section needs an overhaul.  I'll get to it sometime this week, hopefully.  In the meantime, just set `print_settings` to an empty dict.

**Comment by alandmoore** [comment]
Latest commit should deal with this issue.  Please verify.

**Comment by ponchofiesta** [comment]
Just tried it:

```
# python browser.py primo-tu.yaml 
  File "browser.py", line 969
    printer.setPageMargins(*margins, unit)
SyntaxError: only named arguments may follow *expression
```

**Comment by alandmoore** [comment]
Thanks, should be fixed in  c94ebe6

**Comment by alandmoore** [comment]
I believe this issue is resolved in the current codebase.  If you find otherwise, please feel free to open a new issue.

**Comment by ponchofiesta** [comment]
I know I'm far too late and by posting this I'll reopen this issue but to correctly finish this:

Yes, it's fixed

Thank you!
